2025-06-16 13:57:35,604 | INFO | üöÄ Logger initialized at logs\robo_logger_2025-06-16_13-57-35.log
2025-06-16 13:57:46,071 | INFO | Detected task type: REGRESSION
2025-06-16 13:57:46,072 | INFO | üîß Training Models with Hyperparameter Tuning...
2025-06-16 13:57:46,073 | INFO |   Training LinearRegression...
2025-06-16 13:57:46,076 | ERROR |   Skipping LinearRegression due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:46,081 | INFO |   Training DecisionTreeRegressor...
2025-06-16 13:57:51,834 | ERROR |   Skipping DecisionTreeRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:51,835 | INFO |   Training RandomForestRegressor...
2025-06-16 13:57:52,920 | ERROR |   Skipping RandomForestRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:52,921 | INFO |   Training KNeighborsRegressor...
2025-06-16 13:57:52,991 | ERROR |   Skipping KNeighborsRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:52,997 | INFO |   Training SVR...
2025-06-16 13:57:53,198 | ERROR |   Skipping SVR due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:53,199 | INFO |   Training GradientBoostingRegressor...
2025-06-16 13:57:53,653 | ERROR |   Skipping GradientBoostingRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:53,654 | INFO |   Training XGBoostRegressor...
2025-06-16 13:57:54,942 | ERROR |   Skipping XGBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:54,944 | INFO |   Training LightGBMRegressor...
2025-06-16 13:57:56,386 | ERROR |   Skipping LightGBMRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:57:56,388 | INFO |   Training CatBoostRegressor...
2025-06-16 13:58:06,282 | ERROR |   Skipping CatBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 13:58:06,283 | INFO | 
ü§ù Ensemble Models for Regression are not yet implemented.
2025-06-16 13:58:06,283 | INFO | 
‚úÖ All models trained.
