2025-06-16 14:03:48,829 | INFO | üöÄ Logger initialized at logs\robo_logger_2025-06-16_14-03-48.log
2025-06-16 14:03:59,030 | INFO | Detected task type: REGRESSION
2025-06-16 14:03:59,032 | INFO | üîß Training Models with Hyperparameter Tuning...
2025-06-16 14:03:59,032 | INFO |   Training LinearRegression...
2025-06-16 14:03:59,035 | ERROR |   Skipping LinearRegression due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:03:59,039 | INFO |   Training DecisionTreeRegressor...
2025-06-16 14:04:04,366 | ERROR |   Skipping DecisionTreeRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:04,367 | INFO |   Training RandomForestRegressor...
2025-06-16 14:04:05,426 | ERROR |   Skipping RandomForestRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:05,427 | INFO |   Training KNeighborsRegressor...
2025-06-16 14:04:05,483 | ERROR |   Skipping KNeighborsRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:05,508 | INFO |   Training SVR...
2025-06-16 14:04:05,683 | ERROR |   Skipping SVR due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:05,684 | INFO |   Training GradientBoostingRegressor...
2025-06-16 14:04:06,100 | ERROR |   Skipping GradientBoostingRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:06,101 | INFO |   Training XGBoostRegressor...
2025-06-16 14:04:07,325 | ERROR |   Skipping XGBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:07,327 | INFO |   Training LightGBMRegressor...
2025-06-16 14:04:08,565 | ERROR |   Skipping LightGBMRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:08,567 | INFO |   Training CatBoostRegressor...
2025-06-16 14:04:18,596 | ERROR |   Skipping CatBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:04:18,597 | INFO | 
ü§ù Ensemble Models for Regression are not yet implemented.
2025-06-16 14:04:18,597 | INFO | 
‚úÖ All models trained.
2025-06-16 14:07:17,569 | INFO | Detected task type: REGRESSION
2025-06-16 14:07:17,572 | INFO | üîß Training Models with Hyperparameter Tuning...
2025-06-16 14:07:17,572 | INFO |   Training LinearRegression...
2025-06-16 14:07:17,577 | ERROR |   Skipping LinearRegression due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:17,578 | INFO |   Training DecisionTreeRegressor...
2025-06-16 14:07:17,790 | ERROR |   Skipping DecisionTreeRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:17,792 | INFO |   Training RandomForestRegressor...
2025-06-16 14:07:18,717 | ERROR |   Skipping RandomForestRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:18,718 | INFO |   Training KNeighborsRegressor...
2025-06-16 14:07:18,757 | ERROR |   Skipping KNeighborsRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:18,758 | INFO |   Training SVR...
2025-06-16 14:07:19,004 | ERROR |   Skipping SVR due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:19,005 | INFO |   Training GradientBoostingRegressor...
2025-06-16 14:07:19,476 | ERROR |   Skipping GradientBoostingRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:19,477 | INFO |   Training XGBoostRegressor...
2025-06-16 14:07:19,879 | ERROR |   Skipping XGBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:19,881 | INFO |   Training LightGBMRegressor...
2025-06-16 14:07:20,776 | ERROR |   Skipping LightGBMRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:20,777 | INFO |   Training CatBoostRegressor...
2025-06-16 14:07:30,070 | ERROR |   Skipping CatBoostRegressor due to error: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "E:\robo-data-scientist\utils\model_trainer.py", line 183, in train_models
    evaluation_metrics = evaluate_model(trained_model, X_test, y_test, task_type)
  File "E:\robo-data-scientist\utils\model_trainer.py", line 58, in evaluate_model
    "Root Mean Squared Error": mean_squared_error(y_test, y_pred, squared=False),
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 196, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "C:\Program Files\Python310\lib\inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-16 14:07:30,071 | INFO | 
ü§ù Ensemble Models for Regression are not yet implemented.
2025-06-16 14:07:30,071 | INFO | 
‚úÖ All models trained.
