2025-06-16 13:16:01,415 | INFO | ðŸš€ Logger initialized at logs\StreamlitApp_2025-06-16_13-16-01.log
2025-06-16 13:16:20,352 | ERROR | Training Error: 'numpy.ndarray' object has no attribute 'select_dtypes'
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 72, in <module>
    X_processed_for_training, fitted_preprocessor_pipeline = preprocess_data(X_train_raw)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 151, in preprocess_data
    X_processed, preprocessor = builder.fit_transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 145, in fit_transform
    return pipeline.fit_transform(X), pipeline
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 729, in fit_transform
    return last_step.fit_transform(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 996, in fit_transform
    result = self._call_func_on_transformers(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 897, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\parallel.py", line 147, in __call__
    return self.function(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1539, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 717, in fit_transform
    Xt = self._fit(X, y, routed_params)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 587, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1539, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 892, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 92, in fit
    for col in X.select_dtypes(include=['float64', 'int64']).columns:
AttributeError: 'numpy.ndarray' object has no attribute 'select_dtypes'
2025-06-16 13:29:49,115 | ERROR | Training Error: could not convert string to float: 'Toyota'
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 72, in <module>
    X_processed_for_training, fitted_preprocessor_pipeline = preprocess_data(X_train_raw)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 151, in preprocess_data
    X_processed, preprocessor = builder.fit_transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 145, in fit_transform
    return pipeline.fit_transform(X), pipeline
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 717, in fit_transform
    Xt = self._fit(X, y, routed_params)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 587, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1539, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 892, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 73, in fit
    selector.fit(X)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\feature_selection\_variance_threshold.py", line 100, in fit
    X = validate_data(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\validation.py", line 2954, in validate_data
    out = check_array(X, input_name="X", **check_params)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\validation.py", line 1053, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_array_api.py", line 757, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\generic.py", line 2168, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: could not convert string to float: 'Toyota'
2025-06-16 13:30:39,180 | ERROR | Training Error: 'numpy.ndarray' object has no attribute 'select_dtypes'
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 72, in <module>
    X_processed_for_training, fitted_preprocessor_pipeline = preprocess_data(X_train_raw)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 151, in preprocess_data
    X_processed, preprocessor = builder.fit_transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 145, in fit_transform
    return pipeline.fit_transform(X), pipeline
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 729, in fit_transform
    return last_step.fit_transform(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 996, in fit_transform
    result = self._call_func_on_transformers(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 897, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\parallel.py", line 147, in __call__
    return self.function(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1539, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 717, in fit_transform
    Xt = self._fit(X, y, routed_params)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 587, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "E:\robo-data-scientist\venv\lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1539, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\base.py", line 892, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "E:\robo-data-scientist\utils\feature_engineer.py", line 92, in fit
    for col in X.select_dtypes(include=['float64', 'int64']).columns:
AttributeError: 'numpy.ndarray' object has no attribute 'select_dtypes'
2025-06-16 13:31:24,606 | ERROR | Training Error: Estimator skew_correct does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 79, in <module>
    feature_names = fitted_preprocessor_pipeline.named_steps['column_transform'].get_feature_names_out()
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 633, in get_feature_names_out
    feature_names_out = self._get_feature_name_out_for_transformer(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 600, in _get_feature_name_out_for_transformer
    return trans.get_feature_names_out(names)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1264, in get_feature_names_out
    raise AttributeError(
AttributeError: Estimator skew_correct does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?
2025-06-16 13:31:44,950 | ERROR | Training Error: Estimator skew_correct does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 79, in <module>
    feature_names = fitted_preprocessor_pipeline.named_steps['column_transform'].get_feature_names_out()
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 633, in get_feature_names_out
    feature_names_out = self._get_feature_name_out_for_transformer(
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 600, in _get_feature_name_out_for_transformer
    return trans.get_feature_names_out(names)
  File "E:\robo-data-scientist\venv\lib\site-packages\sklearn\pipeline.py", line 1264, in get_feature_names_out
    raise AttributeError(
AttributeError: Estimator skew_correct does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?
2025-06-16 13:33:28,516 | ERROR | Training Error: Length of values (768) does not match length of index (722)
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 85, in <module>
    processed_df_for_training[target_col] = y_train_processed
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\frame.py", line 4316, in __setitem__
    self._set_item(key, value)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\frame.py", line 4529, in _set_item
    value, refs = self._sanitize_column(value)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\frame.py", line 5273, in _sanitize_column
    com.require_length_match(value, self.index)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\common.py", line 573, in require_length_match
    raise ValueError(
ValueError: Length of values (768) does not match length of index (722)
2025-06-16 13:53:06,943 | ERROR | Training Error: 'Accuracy'
Traceback (most recent call last):
  File "E:\robo-data-scientist\app.py", line 107, in <module>
    leaderboard_df = pd.DataFrame(leaderboard_data).sort_values(by="Accuracy", ascending=False)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\frame.py", line 7196, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "E:\robo-data-scientist\venv\lib\site-packages\pandas\core\generic.py", line 1911, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Accuracy'
